export const en = {
  moin: "Hello",
  welc: "Welcome to the Naomi Bächler!",
// Impressum
  impressum: "Imprint",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@proton.com",
  phone: "Telephone: +41 79 659 21 76",
  contentResponsibility: "Responsible for the content according to § 55 Paragraph 2 RStV:",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSwitzerland",
  liability: "Liability-Notice:",
  liabilityText: "Despite careful content control, I assume no liability for the content of external links.\nThe operators of the linked pages are solely responsible for the content of the linked pages.",
  copyright: "Copyright-Notice",
  copyrightText: "The contents and works created by the site operators are subject to Swiss copyright law. Reproduction, processing, distribution, and any kind of exploitation outside the limits of copyright law require the written consent of the respective creator.",
  impressumButton: "Impressum",
// CV
  cvText: "On this page, you will be informed about my educational and non-educational path:",
  school: "I am currently training as an application developer EFZ with a vocational baccalaureate in business at the IMS Bern. This training enables me to acquire knowledge in software development and at the same time integrate economic aspects. Before that, I attended secondary school in Vechigen, primary schools in Utzigen and Littewil and kindergarden in Utzigen. In order to gain practical experience, I took part in various activity days in different companies, which gave me valuable insights into the professional world and strengthened my decision to pursue application development.",
  private: "From 2013 to 2023, I was actively involved in the Scouts, Pfadi Mühlistei in Deiswill near Bern, where I gained a lot of valuable experience in group dynamics and teamwork. In 2014, I discovered my passion for dance at the Alfonsos Ballet School in Boll near Bern, where I developed my dancing skills. Shortly after I immersed myself in the world of figure skating by participating in the Cool Dreams of EC Burgdorf from 2015 to 2017 and I am currently training at EC Münchenbuchsee since 2022. I am also interested in sci-fi novels, which I read with passion, in English and German.",
//Certificates
  certiText: "On this page you can learn about all of the certificates I earned in the past 16 years:",
  ceName: "Name",
  ceDesc: "Description",
  ceDate: "Date",

  ceN1: "Star Test",
  ceD1: "3. level  ice skating",
  ceN2: "Star Test",
  ceD2: "2. level ice skating",
  ceN3: "Emergency Aid",
  ceD3: "Emergency aid course, from Higschool",
  ceN4: "Small Animal Keeper",
  ceD4: "Certificate for keeping small animals",
  ceN5: "WSC",
  ceD5: "Water saftey check",
//Contact
  contText: "If you have any questions regarding content of my website or if you want to contact me:",
  contSp1: "You can do so",
  contSp2: "here",
  contSp3: "!",
//Menu
  home: "Home",
  cv: "CV",
  certi: "Certificates",
  priv: "Private",
  cont: "Contact",
//Home
  hoMe: "About Me :",
  hoTextMe: "My name is Naomi, I am 16 years old, my Myers-Briggs type is ENFP, and I was born in january of 2008. I am studying computer science at the IMS Bern to get my degree in economics and information technologies, with a specialization in application development.\n In my free time I do ice skating and other stuff, you can see more on this topic in the entry on the right.\n\n My whole life, I had my siblings with me, and they are the reason why I generally like people. I am proud to say that my siblings and I have an excellent bond.\n For example, we almost never fight and have active interactions, although we don't live in the same house anymore. Thanks to my father and one of my brothers, computer science is one thing I really like, and thanks to my education, I can improve my knowledge and the application of this knowledge from day to day. \n\n I don't know what my future holds yet, but one of my goals is to join the military, whether in the airborne infantry division or in NBC defense. Another goal I'd like to achieve in life is to travel to different countries, but I'm not quite as ambitious about that yet.\n",
  hoHo: "Hobbies and Interests",
  hoTextHo: "Below are my hobbies which I do on weekends and on fall-, spring- and winter breaks:",
  hoTextIn: "During summer break I usually do the following four activities: gaming, sleeping, swimming and spending time with my kitten. Although I enjoy every listed activity throughout the year.",
//Private
  prText: "Hello World",
  prTextpr: "Here I display all my shool related achievments.",
  prNa: "Username:",
  prPa: "Password:",
  prLoI: "Login",
  prLoU: "Logout",
  prPFT: "Gradesheet File",
  prVC: "Vocational Course Files",
  prDow: "Download my school report",
  prDoV: "Download my course reports",

  prFa: "Subject",
  prGr: "Gradeaverage",
  prSe1: "Semester 1",
  prSe2: "Semester 2",
  prSe3: "Semester 3",
  prSe4: "Semester 4",
  prSe5: "Semester 5",
  prSe6: "Semester 6",

  prFa1: "German",
  prFa2: "French",
  prFa3: "English",  
  prFa4: "Mathematics",  
  prFa5: "Finance and Accounting",
  prFa6: "Economics and Law",
  prFa7: "History and Politics",
  prFa8: "Technology and Environment",
};