export const en = {
  moin: "Hello",
  welc: "Welcome to the Naomi Bächler!",
// Impressum
  impressum: "Imprint",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@proton.com",
  phone: "Telephone: +41 79 659 21 76",
  contentResponsibility: "Responsible for the content according to § 55 Paragraph 2 RStV:",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSwitzerland",
  liability: "Liability-Notice:",
  liabilityText: "Despite careful content control, I assume no liability for the content of external links.\nThe operators of the linked pages are solely responsible for the content of the linked pages.",
  copyright: "Copyright-Notice",
  copyrightText: "The contents and works created by the site operators are subject to Swiss copyright law. Reproduction, processing, distribution, and any kind of exploitation outside the limits of copyright law require the written consent of the respective creator.",
  impressumButton: "Impressum",
//Certificates
  certiText: "On this page you can learn about all of the certificates I earned in the past 16 years:",
  ceName: "Name",
  ceDesc: "Description",
  ceDate: "Date",

  ceN1: "Star Test",
  ceD1: "3. level  ice skating",
  ceN2: "Star Test",
  ceD2: "2. level ice skating",
  ceN3: "Emergency Aid",
  ceD3: "Emergency aid course, from Higschool",
  ceN4: "Small Animal Keeper",
  ceD4: "Certificate for keeping small animals",
  ceN5: "WSC",
  ceD5: "Water saftey check",
//Contact
  contText: "If you have any questions regarding content of my website or if you want to contact me:",
  contSp1: "You can do so",
  contSp2: "here",
  contSp3: "!",
// CV
  cvText: "On this page, you will be informed about my educational and non-educational path:",
  
  cvAdam1: "Learning to become an Application Developer EFZ with a Business Baccalaureate",
  cvAdam2: "IMS Bern",
  cvAdam3: "Gaining expertise in software development and economic aspects through practical training and vocational courses",
  cvBravo1: "Primary & Secondary Education",
  cvBravo2: "Utzigen, Vechigen, Littewil",
  cvBravo3: "Attended primary schools in Utzigen and Littewil, secondary school in OS-Vechigen, with practical activity days across various companiesto gain professional insights",
  cvCharlie1: "Scouting",
  cvCharlie2: "Pfadi Mühlistei, Deiswill",
  cvCharlie3: "Developed teamwork, organisation and leadership skills through active participation in Scouts. Developed quick-reaction time through handeling Kids for one year",
  cvDelta1: "Ballet",
  cvDelta2: "Alfonsos Ballet School",
  cvDelta3: "Started dancing in 2014, developing balance and selfcenter skills at Alfonsos Ballet School",
  cvEdward1: "Ice Skating",
  cvEdward2: "EC Burgdorf",
  cvEdward3: "Participated in figure skating with Cool Dreams for the 1st and 2nd level",
  cvFrank1: "EC Münchenbuchsee",
  cvFrank2: "Currently training at EC Münchenbuchsee for the 4th level",
  cvGeorge1: "Reading Novels",
  cvGeorge2: "English and German",
  cvGeorge3: "Passionate about exploring science fiction and non fiction literature",
//Menu
  home: "Home",
  cv: "CV",
  certi: "Certificates",
  priv: "Private",
  cont: "Contact",
//Home
  hoMe: "About Me :",
  hoTextMe: "My name is Naomi, I am 16 years old, my Myers-Briggs type is ENFP, and I was born in january of 2008. I am studying computer science at the IMS Bern to get my degree in economics and information technologies, with a specialization in application development.\n In my free time I do ice skating and other stuff, you can see more on this topic in the entry on the right.\n\n My whole life, I had my siblings with me, and they are the reason why I generally like people. I am proud to say that my siblings and I have an excellent bond.\n For example, we almost never fight and have active interactions, although we don't live in the same house anymore. Thanks to my father and one of my brothers, computer science is one thing I really like, and thanks to my education, I can improve my knowledge and the application of this knowledge from day to day. \n\n I don't know what my future holds yet, but one of my goals is to join the military, whether in the airborne infantry division or in NBC defense. Another goal I'd like to achieve in life is to travel to different countries, but I'm not quite as ambitious about that yet.\n",
  hoHo: "Hobbies and Interests",
  hoTextHo: "Below are my hobbies which I do on weekends and on fall-, spring- and winter breaks:",
  hoTextIn: "During summer break I usually do the following four activities: gaming, sleeping, swimming and spending time with my kitten. Although I enjoy every listed activity throughout the year.",
//Private
  prText: "Hello World",
  prTextpr: "Here I display all my shool related achievments.",
  prNa: "Username:",
  prPa: "Password:",
  prLoI: "Login",
  prLoU: "Logout",
  prPFT: "Gradesheet File",
  prVC: "Vocational Course Files",
  prDow: "Download my school report",
  prDoV: "Download my course reports",

  prFa: "Subject",
  prGr: "Gradeaverage",
  prSe1: "Semester 1",
  prSe2: "Semester 2",
  prSe3: "Semester 3",
  prSe4: "Semester 4",
  prSe5: "Semester 5",
  prSe6: "Semester 6",

  prFa1: "German",
  prFa2: "French",
  prFa3: "English",  
  prFa4: "Mathematics",  
  prFa5: "Finance and Accounting",
  prFa6: "Economics and Law",
  prFa7: "History and Politics",
  prFa8: "Technology and Environment",
};