export const en = {
  moin: "Hello",
  welc: "Welcome to my online portfolio!",
  logo: "My Logo",
  error: "Invalid Username or Password.",
// Impressum
  impressum: "Imprint",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@protonmail.com",
  phone: "Telephone: +41 79 659 21 76",
  contentResponsibility: "Responsible for the content according to art. 322 paragraph 2 StGB:",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSwitzerland",
  liability: "Liability-Notice:",
  liabilityText: "Despite careful content control, I assume no liability for the content of external links.\nThe operators of the linked pages are solely responsible for the content of the linked pages.",
  copyright: "Copyright-Notice",
  copyrightText: "The contents and works created by the site operators are subject to Swiss copyright law. Reproduction, processing, distribution, and any kind of exploitation outside the limits of copyright law require the written consent of the respective creator.",
  impressumButton: "Imprint",
//Certificates
  certText: "Here is a table containing all of the certificates I earned in the past 16 years:",
  crName: "Name",
  crDesc: "Description",
  crDate: "Date",

  crN1: "Star Test",
  crD1: "3. level  ice skating",
  crD2: "2. level ice skating",
  crD6: "1. level ice skating",
  crN3: "Emergency Aid",
  crD3: "Emergency aid course, from Higschool",
  crN4: "Small Animal Keeper",
  crD4: "Certificate for keeping small animals",
  crN5: "WSC",
  crD5: "Water saftey check",
//Projects
  projText: "On this page you can interact with all my projects",
  lar: "A C# game called LARRY",
  bew: "This Website in a .pdf",
  vow: "My First Website",
  mr: "",
  of: "",
  mew: "",
  lr: "",
  
//Contact
  contText: "If you have any questions regarding contents of my website or if you want to contact me,",
  contSp1: "you can do so",
  contSp2: "here",
  contSp3: "!",
// CV
  cvText: "On this page, you will be informed about my educational and non-educational path:",

  cvAdam1: "Learning to become an Application Developer EFZ with a Business Baccalaureate",
  cvAdam2: "IMS Bern",
  cvAdam3: "Gaining expertise in software development and economic aspects through practical training and vocational courses.",
  cvBravo1: "Primary & Secondary Education",
  cvBravo2: "Utzigen, Littewil, Vechigen",
  cvBravo3: "Attended primary schools in Utzigen and Littewil, secondary school in OS-Vechigen, with practical activity days across various companies to gain professional insights.",
  cvCharlie1: "Scouts",
  cvCharlie2: "Pfadi Mülistei, Deiswill",
  cvCharlie3: "Developed teamwork, organisation and leadership skills through active participation in the Scouts for ten years. Developed quick-reaction time through handeling Kids for one year.",
  cvDelta1: "Ballet",
  cvDelta2: "Alfonsos Ballet School",
  cvDelta3: "Started dancing in 2014, developing balance and selfcenter skills at Alfonsos Ballet School.",
  cvEdward1: "Ice Skating",
  cvEdward3: "Participated in figure skating with Cool Dreams for the 1st and 2nd level",
  cvFrank1: "Currently training at EC Münchenbuchsee for the 4th level",
  cvGeorge1: "Reading Novels",
  cvGeorge2: "English and German",
  cvGeorge3: "Passionate about exploring fantasy and non-fiction literature",
  cvHarley2: "Pfadi Patria, Bern",
  cvHarley3: "In the summer of 2025 I became a Groupleader ...",
//Menu
  home: "My World",
  cv: "Resume",
  proj: "Projects",
  priv: "Skill Vault",
  cont: "Contact",
//Home
  hoMe: "About Me :",
  hoTextMe: "My name is Naomi, I am 17 years old, I was born in january of 2008 and my Myers-Briggs type is ENFP. I am studying computer science at the IMS Bern to get my degree in economics and information technologies, with a specialization in application development.\n In my free time I do ice skating and other stuff, you can see more on this topic in the entry on the right.\n\n My whole life, I had my siblings with me, and they are the reason why I generally like people. I am proud to say that my siblings and I have an excellent bond.\n For example, we almost never fight and have active interactions, although we don't live in the same house anymore. Thanks to my father and one of my brothers, computer science is one thing I really like, and thanks to my education, I can improve my knowledge and the application of this knowledge from day to day. \n\n I don't know what my future holds yet, but one of my goals is to join the military, whether in the airborne infantry division or in NBC defense. Another goal I'd like to achieve in life is to travel to different countries, but I'm not quite as ambitious about that yet.\n",
  hoHo: "Hobbies and Interests",
  hoTextHo: "Below are my hobbies which I do on weekends and on fall-, spring- and winter breaks:",
  hoTextIn: "During summer break I usually do the following four activities: gaming, sleeping, swimming and spending time with my kitten. Although I enjoy every listed activity throughout the year.",
  
  adam: "Me working",
  bravo: "SwitzerLAN",
  charlie: "My Family",
  delta: "Me grilling",
  edward: "Archery",
  frank: "My cute cat!",
  
  ba: "Baking",
  bad: "I bake mostly Brownies, Cookies, Pancakes and other sweets",
  bu: "Reading",
  bud: "I read books ever since I have been 7 years old, mostly sci-fi novels.\n Such as Harry Potter, The Hobbit or The Disc World Novels",
  da: "Dancing",
  dad: "I enjoy dancing, both classical and freestyle",
  ic: "Iceskating",
  icd: "I first stepped on the ice with 2 years old, since then it has captivated me",
  dn: "Dungeons and Dragons",
  dnd: "I have been playing Dungeons and Dragons since I am 15 years old and I really enjoy it",
  pc: "Computer games",
  pcd: "I have been fascinated by PC games ever since I was little, be it creating them or playing them",
  bw: "Archery",
  bwd: "I shot my first arrow at 8 years old and recently even made my own bow,",
  mu: "Listening to music",
  mud: "Music plays a huge role in my life; I listen to it at almost any time of the day",
//Private
  prText: "Here I display all my shool related achievments.",
  prNa: "Username",
  prPa: "Password",
  prLoI: "Login",
  prLoU: "Logout",
  prPFT: "Gradesheets",
  prVC: "Vocational Courses",
  prPra: "Practical Training",
  prDow: "Download all my reports",

  z1: "Gradesheet first year",
  z2: "Gradesheet second year",

  m187: "Module 187, PC's and ergonomic workplace",
  m106: "Module 106, SQL database",
  m210: "Module 210, Cloud and Azure",
  m294: "Module 294, Frontend Development",
  m295: "Module 295, Backend Development",
  m335: "Module 335, React Mobile App",

  hs: "Fallsemester ",
  fs: "Springsemester ",
};