export const fr = {
  moin: "Bonjour",
  welc: "Bienvenue sur mon portfolio en ligne!",
  logo: "Mon Logo",
//Impressum
  impressum: "Mentions légales",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@protonmail.com",
  phone: "Téléphone: +41 79 659 21 76",
  contentResponsibility: "Responsable du contenu selon art. 322 § 2 StGB:",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSuisse",
  liability: "Avis de responsabilité:",
  liabilityText: "Malgré un contrôle minutieux du contenu, je décline toute responsabilité pour le contenu des liens externes.\nLes opérateurs des pages liées sont uniquement responsables du contenu des pages liées.",
  copyright: "Avis de droit d'auteur",
  copyrightText: "Les contenus et œuvres créés par les opérateurs de ce site sont soumis au droit d'auteur suisse. La reproduction, le traitement, la diffusion et toute exploitation en dehors des limites du droit d'auteur nécessitent le consentement écrit du créateur.",
  impressumButton: "Mentions légales",
// CV
  cvText: "Sur cette page, vous serez informé de mon parcours éducatif et non éducatif :",

  cvAdam1: "Apprendre à devenir développeur d'applications EFZ avec un baccalauréat commercial",
  cvAdam2: "IMS Berne",
  cvAdam3: "Acquérir une expertise en matière de développement de logiciels et d'aspects économiques grâce à une formation pratique et à des cours professionnels",
  cvBravo1: "École primaire et secondaire",
  cvBravo2: "Utzigen, Littewil, Vechigen",
  cvBravo3: "Participation aux écoles primaires d'Utzigen et de Littewil, à l'école secondaire d'OS-Vechigen, avec des journées d'activités pratiques dans diverses entreprises afin d'acquérir des connaissances professionnelles",
  cvCharlie1: "Scout",
  cvCharlie2: "Schout Mülistei, Deiswill",
  cvCharlie3: "Développement du travail d'équipe, de l'organisation et des compétences en matière de leadership grâce à une participation active aux scouts. Développement d'un temps de réaction rapide par la prise en charge d'enfants pendant un an",
  cvDelta1: "Ballet",
  cvDelta2: "École de ballet d'Alfonso",
  cvDelta3: "A commencé à danser en 2014, développant l'équilibre et le centrage sur soi à l'école de ballet Alfonsos",
  cvEdward1: "Patinage artistique",
  cvEdward3: "Participation au patinage artistique avec Cool Dreams pour les 1er et 2ème niveaux",
  cvFrank1: "Actuellement en formation à l'EC Münchenbuchsee pour le 4ème niveau",
  cvGeorge1: "Lire des romans",
  cvGeorge2: "Allemand et anglais",
  cvGeorge3: "Passionné par l'exploration de la littérature de science-fiction et de non-fiction",
  //Certificates
  certText: "Ici vous trouverez tous les certificats que j’ai obtenus au cours des 16 dernières années:",
  crName: "Nom",
  crDesc: "Description",
  crDate: "Date",

  crN1: "Test d’étoile",
  crD1: "Patinage sur glace niveau 3",
  crN2: "Test d’étoile",
  crD2: "Patinage sur glace niveau 2",
  crN3: "Secours d’urgence",
  crD3: "Cours de secourisme, niveau lycée",
  crN4: "Soigneur de petits animaux",
  crD4: "Certificat de garde de petits animaux",
  crN5: "WSC",
  crD5: "Contrôle de sécurité aquatique",
  crD6: "Patinage sur glace niveau 1", 
//Projects
  projText: "Sur cette page, vous pouvez interagir avec tous mes projets",
//Contact
  contText: "Si vous avez encore des questions concernantes le contenu de mon site web ou si vous souhaitez me contacter,",
  contSp1: "vous pouvez le faire",
  contSp2: "ici",
  contSp3: "!",
//Menu
  home: "Mon Monde",
  cv: "Curriculum",
  proj: "Projets",
  priv: "Tésor des Compétences",
  cont: "Contact",
//Home
  hoMe: "À propos de moi",
  hoTextMe: "Je m'appelle Naomi, j'ai 17 ans, je suis née en janvier 2008 et mon type Myers-Briggs est ENFP. J'étudie l'informatique à l'IMS de Berne, avec une maturité professionnelle en commerce et un diplôme fédéral en développement d'applications.\nPendant mon temps libre, je fais du patin à glace et d'autres activités. Vous trouverez plus d'informations à ce sujet dans l'article de droite.\n\nMes frères et sœur m'accompagnent depuis toujours et c'est grâce à eux que j'apprécie les gens. Je suis fier de la merveilleuse relation que nous entretenons avec eux.\n Par exemple, nous ne nous disputons presque jamais et communiquons activement, même si nous ne vivons plus sous le même toit. Grâce à mon père et à l'un de mes frères, j'apprécie beaucoup l'informatique, et grâce à mes études, je peux améliorer mes connaissances et les mettre en pratique chaque jour.\n\nJe ne sais pas encore ce que l'avenir me réserve, mais l'un de mes objectifs est de m'engager dans l'armée, que ce soit dans la division d'infanterie aéroportée ou dans la défense NBC. J'aimerais aussi voyager dans différents pays, mais je ne suis pas encore aussi ambitieux.\n",
  hoHo: "Loisirs et centres d’intérêt",
  hoTextHo: "Voici mes loisirs, que je pratique le week-end et pendant les vacances d’automne, de printemps et d’hiver :",
  hoTextIn: "Pendant les vacances d’été, je me consacre généralement aux quatre activités suivantes : jouer, dormir, nager et passer du temps avec mon chaton. J’apprécie chacune de ces activités toute l’année.",
  
  adam: "Moi au travail",
  bravo: "SwitzerLAN",
  charlie: "Ma famille",
  delta: "Moi en train de griller",
  edward: "Au tir à l'arc",
  frank: "Mon doux chat!",
  
  ba: "Cuisiner",
  bad: "Je cuisine surtout des brownies, des biscuits, des pancakes et d'autres douceurs ",
  bu: "Lire",
  bud: "Je lis des livres depuis l'âge de 7 ans, principalement des romans de science-fiction. Par exemple Harry Potter, Le Hobbit ou les romans du Disque-Monde",
  da: "Danse",
  dad: "J'aime danser, aussi bien le classique que le freestyle",
  ic: "Patinage artistique",
  icd: "J'ai chaussé mes premiers patins à glace à l'âge de 2 ans et depuis, je suis tombé sous le charme",
  dn: "Donjons et Dragons",
  dnd: "Je joue à Donjons et Dragons depuis l'âge de 15 ans et j'adore ça",
  pc: "Jeux PC",
  pcd: " Depuis que je suis petit, je suis fasciné par les jeux PC, que ce soit pour les créer ou pour y jouer",
  bw: "Tir à l'arc",
  bwd: " J'ai tiré mes premières flèches à l'âge de 8 ans et j'ai même fabriqué mon propre arc récemment",
  mu: "Écouter de la musique",
  mud: "La musique joue un rôle énorme dans ma vie, j'en écoute à presque tout moment de la journée",
//Private
  prText: "Ici, j'affiche toutes mes réalisations liées à l'école",  
  prNa: "Nom d'utilisatuer:",
  prPa: "Mot de passe:",
  prLoI: "Connexion",
  prLoU: "Déconnexion",
  prPFT: "Fichier de relevés de notes",
  prVC: "Fichiers de cours professionnels",
  prDow: "Télécharger mon rapport école",
  prDoV: "Télécharger mes rapports de cours",

  prFa: "Sujet",
  prGr: "Note moyenne",
  prSe1: "Semestre 1",
  prSe2: "Semestre 2",
  prSe3: "Semestre 3",
  prSe4: "Semestre 4",
  prSe5: "Semestre 5",
  prSe6: "Semestre 6",
  
  prFa1: "Allemand",
  prFa2: "Français",
  prFa3: "Anglais",
  prFa4: "Mathématiques",
  prFa5: "Finance et comptabilité",
  prFa6: "Économie et droit",
  prFa7: "Histoire et politique",
  prFa8: "Technologie et environnement",
};