export const fr = {
  moin: "Bonjour",
  welc: "Bienvenue chez Naomi Bächler !",
//Impressum
  impressum: "Mentions légales",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@proton.com",
  phone: "Téléphone: +41 79 659 21 76",
  contentResponsibility: "Responsable du contenu selon § 55 Absatz 2 RStV:",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSuisse",
  liability: "Avis de responsabilité:",
  liabilityText: "Malgré un contrôle minutieux du contenu, je décline toute responsabilité pour le contenu des liens externes.\nLes opérateurs des pages liées sont uniquement responsables du contenu des pages liées.",
  copyright: "Avis de droit d'auteur",
  copyrightText: "Les contenus et œuvres créés par les opérateurs de ce site sont soumis au droit d'auteur suisse. La reproduction, le traitement, la diffusion et toute exploitation en dehors des limites du droit d'auteur nécessitent le consentement écrit du créateur.",
  impressumButton: "Mentions légales",
// CV
  cvText: "Sur cette page, vous serez informé de mon parcours éducatif et non éducatif :",
  school: "Je suis actuellement en formation d'application developer EFZ avec un baccalauréat professionnel en commerce à l'IMS Bern. Cette formation me permet d'acquérir des connaissances en développement logiciel tout en intégrant des aspects économiques. Avant cela, j'ai fréquenté le lycée à Vechigen, l'école primaire à Utzigen et Littewil, ainsi que la maternelle à Utzigen. Afin d'acquérir une expérience pratique, j'ai participé à diverses journées d'activités dans différentes entreprises, ce qui m'a permis d'obtenir des insights précieux sur le monde professionnel et de renforcer ma décision de poursuivre le développement d'applications.",
  private: "De 2013 à 2023, j'ai été activement impliqué dans les Scouts, Pfadi Mühlistei à Deiswill près de Bern, où j'ai acquis beaucoup d'expérience en dynamique de groupe et en travail d'équipe. En 2014, j'ai découvert ma passion pour la danse à l'École de ballet Alfonsos à Boll près de Bern, où j'ai développé mes compétences en danse. Peu de temps après, je me suis immergé dans le monde du patinage artistique en participant aux Cool Dreams du EC Burgdorf de 2015 à 2017 et je m'entraîne actuellement à EC Münchenbuchsee depuis 2022. Je suis également passionné par les romans de science-fiction, que je lis avec passion, en anglais et en allemand.",
//Certificates
  certiText: "Sur cette page, vous trouverez tous les certificats que j’ai obtenus au cours des 16dernières années:",
  ceName: "Nom",
  ceDesc: "Description",
  ceDate: "Date",

  ceN1: "Test d’étoile",
  ceD1: "Patinage sur glace niveau3",
  ceN2: "Test d’étoile",
  ceD2: "Patinage sur glace niveau2",
  ceN3: "Secours d’urgence",
  ceD3: "Cours de secourisme, niveau lycée",
  ceN4: "Soigneur de petits animaux",
  ceD4: "Certificat de garde de petits animaux",
  ceN5: "WSC",
  ceD5: "Contrôle de sécurité aquatique",
//Contact
  contText: "Si vous avez encore des questions concernant le contenu de mon site Web ou si vous souhaitez me contacter autrement :",
  contSp1: "Vous pouvez le faire",
  contSp2: "ici",
  contSp3: "!",
//Menu
  home: "Accueil",
  cv: "CV",
  certi: "Certificats",
  priv: "Privé",
  cont: "Contact",
//Home
  hoMe: "À propos de moi",
  hoTextMe: "Je m'appelle Naomi, j'ai 16 ans, mon type Myers-Briggs est ENFP et je suis née en janvier 2008. J'étudie l'informatique à l'IMS de Berne, avec une maturité professionnelle en commerce et un diplôme fédéral en développement d'applications.\nPendant mon temps libre, je fais du patin à glace et d'autres activités. Vous trouverez plus d'informations à ce sujet dans l'article de droite.\n\nMes frères et sœur m'accompagnent depuis toujours et c'est grâce à eux que j'apprécie les gens. Je suis fier de la merveilleuse relation que nous entretenons avec eux.\n Par exemple, nous ne nous disputons presque jamais et communiquons activement, même si nous ne vivons plus sous le même toit. Grâce à mon père et à l'un de mes frères, j'apprécie beaucoup l'informatique, et grâce à mes études, je peux améliorer mes connaissances et les mettre en pratique chaque jour.\n\nJe ne sais pas encore ce que l'avenir me réserve, mais l'un de mes objectifs est de m'engager dans l'armée, que ce soit dans la division d'infanterie aéroportée ou dans la défense NBC. J'aimerais aussi voyager dans différents pays, mais je ne suis pas encore aussi ambitieux.\n",
  hoHo: "Loisirs et centres d’intérêt",
  hoTextHo: "Voici mes loisirs, que je pratique le week-end et pendant les vacances d’automne, de printemps et d’hiver :",
  hoTextIn: "Pendant les vacances d’été, je me consacre généralement aux quatre activités suivantes : jouer, dormir, nager et passer du temps avec mon chaton. J’apprécie chacune de ces activités toute l’année.",
//Private
  prText: "Bonjour le monde",
  prTextpr: "Ici, j'affiche toutes mes réalisations liées à l'école",  
  prNa: "Nom d'utilisatuer:",
  prPa: "Mot de passe:",
  prLoI: "Connexion",
  prLoU: "Déconnexion",
  prPFT: "Fichier de relevés de notes",
  prVC: "Fichiers de cours professionnels",
  prDow: "Télécharger mon rapport école",
  prDoV: "Télécharger mes rapports de cours",

  prFa: "Sujet",
  prGr: "Note moyenne",
  prSe1: "Semestre 1",
  prSe2: "Semestre 2",
  prSe3: "Semestre 3",
  prSe4: "Semestre 4",
  prSe5: "Semestre 5",
  prSe6: "Semestre 6",
  
  prFa1: "Allemand",
  prFa2: "Français",
  prFa3: "Anglais",
  prFa4: "Mathématiques",
  prFa5: "Finance et comptabilité",
  prFa6: "Économie et droit",
  prFa7: "Histoire et politique",
  prFa8: "Technologie et environnement",
};