export const fr = {
  moin: "Bonjour",
  welc: "Bienvenue sur mon site web!",
  logo: "Mon Logo",
  error: "Nom d'utilisateur ou mot de passe invalide.",
//Impressum
  impressum: "Mentions légales",
  contact: "Contact:",
  email: "E-Mail: naomi.baechler@protonmail.com",
  phone: "Téléphone: +41 79 659 21 76",
  contentResponsibility: "Responsable du contenu selon art. 322 al. 2 CP",
  contentDetails: "Naomi Bächler\nWuhlstrasse 38\n3068 Utzigen\nSuisse",
  liability: "Clause de non-responsabilité:",
  liabilityText: "Malgré un contrôle minutieux du contenu, je décline toute responsabilité pour le contenu des liens externes.\nLes opérateurs des pages liées sont uniquement responsables du contenu des pages liées.",
  copyright: "Droit d'auteur",
  copyrightText: "Les contenus et œuvres créés par les opérateurs de ce site sont soumis au droit d'auteur suisse. La reproduction, le traitement, la diffusion et toute exploitation en dehors des limites du droit d'auteur nécessitent le consentement écrit du créateur.",
  impressumButton: "Mentions légales",
//Contact
  contText: "Si vous avez encore des questions concernantes le contenu de mon site web ou si vous souhaitez me contacter,",
  contSp1: "vous pouvez le faire",
  contSp2: "ici",
  contSp3: "!",
// CV
  cvText: "Sur cette page, vous trouverez des informations sur mon parcours scolaire et extrascolaire :",

  cvAdam1: "En formation d’informaticienne CFC en développement d’applications avec maturité professionnelle en économie",
  cvAdam2: "IMS Berne",
  cvAdam3: "Acquérir une expertise en matière de développement de logiciels et d'aspects économiques grâce à une formation pratique et à des cours interentreprises",
  cvBravo1: "École primaire et secondaire",
  cvBravo2: "Utzigen, Littewil, Vechigen",
  cvBravo3: "Scolarité aux écoles primaires d'Utzigen et de Littewil, à l'école secondaire OS Vechigen, avec des journées de stage dans diverses entreprises afin d'acquérir des expérience professionnelles",
  cvCharlie1: "Scout",
  cvCharlie2: "Scout Mülistei, Deiswill",
  cvCharlie3: "Acquisition de compétences en travail d’équipe, en organisation et en leadership grâce à dix années d’engagement scout. Développement de la rapidité de réaction grâce à une année de surveillance d’enfants.",
  cvDelta1: "Ballet",
  cvDelta2: "École de ballet d'Alfonso",
  cvDelta3: "Début de la danse en 2014, développement de l’équilibre et de la recentration sur soi à l’école de ballet d'Alfonso.",
  cvEdward1: "Patinage artistique",
  cvEdward3: "Participation au patinage artistique avec Cool Dreams aux niveaux 1 et 2",
  cvFrank1: "En préparation du niveau 4 à l’EC Münchenbuchsee",
  cvGeorge1: "Lire des romans",
  cvGeorge2: "Allemand et anglais",
  cvGeorge3: "Passionné par l'exploration de la littérature de science-fiction et de non-fiction",
  cvHarley2: "Pfadi Patria, Berne",
  cvHarley3: "Active depuis l'été 2025 en tant que responsable dans la branche scouts.",
//Certificates
  certText: "Ici vous trouverez tous les certificats que j’ai obtenus au cours des 16 dernières années:",
  crName: "Nom",
  crDesc: "Description",
  crDate: "Date",

  crN1: "Test d’étoile",
  crD1: "Patinage artistique niveau 3",
  crD2: "Patinage artistique niveau 2",
  crD6: "Patinage artistique niveau 1", 
  crN3: "Détention de petits animaux",
  crD3: "Cours de secourisme, niveau lycée",
  crN4: "Soigneur de petits animaux",
  crD4: "Certificat pour détenir des petits animaux",
  crN5: "CSA",
  crD5: "Contrôle de sécurité aquatique",
//Projects
  projText: "Sur cette page, vous pouvez interagir avec tous mes projets",
  lar: "Un jeu C# du nome LARRY",
  bew: "Cette site web, en React et Next.js ",
  vow: "Mon premier site web, en HTML, CSS et JavaScript",
  mr: "Un Marsrover-roboteur python projet",
  of: "Un app pour Orellfüssli en .NET Maui",
  mew: "Un site web focusing dans UX/UI-aspects, en HTML et CSS",
  lr: "Mon premier project, Llama Race",
  no: "Notora un app mobile en react, pour combiné multiple apps dans une",
  tt: "",
  nsq: "",
  anae: "",
  tub: "",
  lang: "Langues",
//Menu
  home: "Mon Monde",
  cv: "Curriculum vitae",
  proj: "Projets",
  priv: "Coffre-fort des Compétences",
  cont: "Contact",
//Home
  hoMe: "À propos de moi",
  hoTextMe: "Je m'appelle Naomi, j'ai 17 ans, je suis née en janvier 2008 et mon type Myers-Briggs est ENFP. J'étudie l'informatique à l'IMS de Berne, avec une maturité professionnelle en commerce et un CFC en développement d'applications.\nPendant mon temps libre, je fais du patin à glace et d'autres activités. Vous trouverez plus d'informations à ce sujet dans l'article à droite.\n\nMes frères et sœur m'accompagnent depuis toujours et c'est grâce à eux que j'apprécie les gens. Je suis fière de la merveilleuse relation que nous entretenons ensemble.\n Par exemple, nous ne nous disputons presque jamais et communiquons activement, même si nous ne vivons plus sous le même toit. Grâce à mon père et à l'un de mes frères, j'apprécie beaucoup l'informatique, et grâce à mes études, je peux améliorer mes connaissances et les mettre en pratique chaque jour.\n\nJe ne sais pas encore ce que l'avenir me réserve, mais l'un de mes objectifs est de m'engager dans l'armée, que ce soit dans la division d'infanterie aéroportée ou dans la défense NBC. J'aimerais aussi voyager dans différents pays, mais je ne suis pas encore aussi ambitieux.\n",
  hoHo: "Loisirs et centres d’intérêt",
  hoTextHo: "Voici mes loisirs, que je pratique le week-end et pendant les vacances d’automne, de printemps et d’hiver :",
  hoTextIn: "Pendant les vacances d’été, je me consacre généralement aux quatre activités suivantes : jouer, dormir, nager et passer du temps avec mon chaton. J’apprécie chacune de ces activités toute l’année.",
  
  adam: "Moi au travail",
  bravo: "SwitzerLAN",
  charlie: "Ma famille",
  delta: "Moi en train de griller",
  edward: "Au tir à l'arc",
  frank: "Mon doux chat!",
  
  ba: "Cuisiner",
  bad: "Je cuisine surtout des brownies, des biscuits, des pancakes et d'autres douceurs ",
  bu: "Lire",
  // Fantasy -> fr anstadt sci fi
  bud: "Je lis des livres depuis l'âge de 7 ans, principalement des romans de science-fiction. Par exemple Harry Potter, Le Hobbit ou les romans du Disque-Monde",
  da: "Danser",
  dad: "J'aime danser, aussi bien le classique que le freestyle",
  ic: "Patinage artistique",
  icd: "J'ai chaussé mes premiers patins à glace à l'âge de 2 ans et depuis, je suis tombé sous le charme",
  dn: "Donjons et Dragons",
  dnd: "Je joue à Donjons et Dragons depuis l'âge de 15 ans et j'adore ça",
  pc: "Jeux vidéo",
  pcd: " Depuis que je suis petit, je suis fasciné par les jeux PC, que ce soit pour les créer ou pour y jouer",
  bw: "Tir à l'arc",
  bwd: " J'ai tiré mes premières flèches à l'âge de 8 ans et j'ai même fabriqué mon propre arc récemment",
  mu: "Écouter de la musique",
  mud: "La musique joue un rôle énorme dans ma vie, j'en écoute à presque tout moment de la journée",
//Private
  prText: "Ici, j'affiche toutes mes réalisations liées à l'école",  
  prNa: "Nom d'utilisatuer:",
  prPa: "Mot de passe:",
  prLoI: "Connexion",
  prLoU: "Déconnexion",
  prPFT: "Fichiers de bulletin scolaire",
  prVC: "Fichiers de cours interentreprises",
  prPra: "Fichiers de cours practical",
  prDow: "Télécharger mon bulletin scolaire",

  z1: "Ané Un",
  z2: "Ané Duex",

  m187: "Modulé 187, ",
  m106: "M 106, ",
  m210: "M 210, ",
  m294: "M 294, ",
  m295: "M 295, ",
  m335: "M 335, ",

  hs: "trimestre d'autune ",
  fs: "trimestre de printemps ",

};